import 'package:json_annotation/json_annotation.dart';

part 'trip_request_dto.g.dart'; // This will be generated by json_serializable

@JsonSerializable(
  explicitToJson: true,
  genericArgumentFactories: true,
  fieldRename: FieldRename.snake,
)
class TripRequestDto {
  // "startTime": "string",
  // "endTime": "string",
  // "vehicleNumber": "string"

  // Constructor
  TripRequestDto({
    required this.driverId,
    required this.material,
    required this.loadingAreaId,
    required this.unloadingAreaId,
    required this.projectId,
    this.startTime,
    this.vehicleNumber,
    this.endTime,
  });

  // Factory method for creating a TripRequestDto from JSON
  factory TripRequestDto.fromJson(Map<String, dynamic> json) =>
      _$TripRequestDtoFromJson(json);
  final int driverId;
  final String material;
  final int loadingAreaId;
  final int unloadingAreaId;
  final int projectId;
  final String? startTime;
  final String? vehicleNumber;
  final String? endTime;

  // Method for converting TripRequestDto to JSON
  Map<String, dynamic> toJson() => _$TripRequestDtoToJson(this);
}
