// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_E1cq-GcDedIqVLNZM4NTalrfsGRsq4',
    appId: '1:1070249987319:android:947a6afa05b97ffd1c17f2',
    messagingSenderId: '1070249987319',
    projectId: 'dumpshine-travel',
    storageBucket: 'dumpshine-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxwUgt59fMd-VE13YK7BFmkfruKO3mCcE',
    appId: '1:1070249987319:ios:e7daeaee705006e81c17f2',
    messagingSenderId: '1070249987319',
    projectId: 'dumpshine-travel',
    storageBucket: 'dumpshine-travel.firebasestorage.app',
    iosBundleId: 'ys.com.shinedump',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Ktuw6FeR3biPT6zLYrY5QEjaPVltoz0',
    appId: '1:752213925745:ios:1ff41163763219be3de0d0',
    messagingSenderId: '752213925745',
    projectId: 'gps-tracking-b8cf3',
    storageBucket: 'gps-tracking-b8cf3.firebasestorage.app',
    iosBundleId: 'ys.com.shinedump',
  );
}